# Generated by Django 3.0.8 on 2020-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/image/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
