# Generated by Django 3.0.8 on 2020-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Biology', 'Biology'), ('Physical Education', 'Physical Education'), ('Business', 'Business'), ('Economics', 'Economics')], default='other', max_length=64),
        ),
    ]
