# Generated by Django 3.0.8 on 2020-10-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201028_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='uni',
        ),
    ]
