# Generated by Django 3.0.8 on 2020-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201030_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='uni',
        ),
    ]
