# Generated by Django 3.0.8 on 2020-10-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_posts_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='university',
            field=models.CharField(choices=[('KFUPM', 'KFUPM'), ('Harvard', 'Harvard')], default='other', max_length=64),
        ),
    ]
