# Generated by Django 3.0.8 on 2020-10-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_follow_likes_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='university',
        ),
    ]
