# Generated by Django 3.0.8 on 2020-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201101_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.IntegerField(),
        ),
    ]
