# Generated by Django 3.0.8 on 2020-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='pic',
            field=models.CharField(default='/media/profile/image/DSC_0054.JPG', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='temp', max_length=256),
            preserve_default=False,
        ),
    ]
