# Generated by Django 3.0.8 on 2020-11-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201102_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
