# Generated by Django 3.0.8 on 2020-11-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_posts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('question', 'Question'), ('file', 'File Share'), ('rant', 'Rant')], default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='doc',
            field=models.FileField(blank=True, upload_to='posts/doc/'),
        ),
    ]
