# Generated by Django 3.0.8 on 2020-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201123_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('question', 'Question'), ('file', 'File Share'), ('rant', 'Rant')], default='question', max_length=64),
        ),
    ]
