# Generated by Django 3.0.8 on 2020-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201123_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='posts/doc/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='subject',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Biology', 'Biology'), ('Physical Education', 'Physical Education'), ('Business', 'Business'), ('Economics', 'Economics')], default='other', max_length=64),
        ),
    ]
