# Generated by Django 3.0.8 on 2020-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201123_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='doc',
            field=models.FileField(default='null', upload_to='posts/doc/'),
        ),
    ]
