# Generated by Django 3.0.8 on 2020-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20201123_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('Question', 'Question'), ('File Share', 'File Share'), ('Rant', 'Rant')], default='question', max_length=64),
        ),
    ]
