# Generated by Django 3.0.8 on 2020-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('Question', 'Question'), ('Content Share', 'Content Share'), ('Rant', 'Rant')], default='question', max_length=64),
        ),
    ]
