# Generated by Django 3.0.8 on 2021-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201210_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='level',
            field=models.CharField(choices=[('Preparatory', 'Preparatory'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=64),
        ),
    ]
